Admin 미션 추가/조회 API 구현
PEACH-BROS/lets-merge pull request #13
Opened 2020-05-29 15:53 UTC by YebinK

2020-06-09 07:20 UTC, pci2676 requested changes
피드백 반영해주라~

2020-06-09 07:20 UTC, pci2676 commented on src/main/java/com/peachbros/letsmerge/mission/service/MissionService.java
> +    @Transactional(readOnly = true)
굳이 지금은 트랜잭션을 메소드 단위로 걸어 놓을 필요가 없을것 같아.
여러번의 조회가 발생하는게 아닌이상 트랜잭션을 거는 것이 성능의 저하를 일으키니까 조회 로직이 복잡해지면 그때 메소드 레벨로 트랜잭션을 걸도록 하는게 어때?

2020-06-09 07:20 UTC, pci2676 commented on src/main/java/com/peachbros/letsmerge/mission/service/MissionService.java
> +    public void deleteMission(Long missionId) {
오히려 이쪽에 트랜잭션을 꼭 걸어주는게 좋을 것 같아

2020-06-09 07:20 UTC, pci2676 commented on src/main/java/com/peachbros/letsmerge/mission/service/MissionService.java
> +    public void deleteMissions() {
테스트를 위한 메서드는 제거해주라

2020-06-09 13:59 UTC, YebinK commented on src/main/java/com/peachbros/letsmerge/mission/service/MissionService.java
> +    @Transactional(readOnly = true)
좋은 생각이야!
어노테이션 습관적으로 붙이고 있었는데 앞으로 신경 써서 달아야겠다!

2020-06-09 14:02 UTC, YebinK commented on src/main/java/com/peachbros/letsmerge/mission/service/MissionService.java
> +    public void deleteMission(Long missionId) {
오케이 확인
잘 구분해서 써야겠다.

2020-06-09 14:09 UTC, YebinK commented on src/main/java/com/peachbros/letsmerge/mission/service/MissionService.java
> +    public void deleteMissions() {
인수 테스트에서 db truncate 하려고 만들어둔건데, 저 메소드 대신 테스트에서 MissionRepository 호출하도록 바꿨어!

2020-06-09 14:10 UTC, YebinK commented
피드백 반영했습니다~ 🙂

2020-06-09 14:12 UTC, pci2676 approved these changes
확인~

2020-06-10 11:03 UTC, ghost approved these changes
변경되면 좋을 것 같거나 제가 모를 것 같은 것을 짚어봤는데 의도를 설명해주시면 좋겠어요

2020-06-10 11:03 UTC, ghost commented on src/main/java/com/peachbros/letsmerge/core/ErrorCode.java
> +    MATCHER_EXCEPTION(4000, "매쳐 익셉션");
아직 발생할 에러의 종류가 적어서 이렇게 분리하신 건가요 ??

세분화할 여지가 없나요?!

2020-06-10 11:03 UTC, ghost commented on src/main/java/com/peachbros/letsmerge/mission/model/domain/Mission.java
> +            throw new IllegalArgumentException(String.format("시작 시간(%s)이 종료 시간(%s)보다 뒤에 있습니다.", startDateTime, dueDateTime));
Exception을 커스텀하지 않은 이유가 있을까요?

2020-06-10 11:03 UTC, ghost commented on src/main/java/com/peachbros/letsmerge/mission/service/MissionService.java
> +
공백을 제거해보자!

2020-06-10 11:03 UTC, ghost commented on src/main/java/com/peachbros/letsmerge/mission/web/MissionController.java
>  public class MissionController {
`@RequestMapping("/admin/missions")` 로 통일하는 건 어떨까요?

2020-06-10 11:42 UTC, YebinK commented on src/main/java/com/peachbros/letsmerge/core/ErrorCode.java
> +    MATCHER_EXCEPTION(4000, "매쳐 익셉션");
우선 큰 틀만 잡아두고, 에러가 예상될 때마다 종류에 따라 소분류(100번대)로 추가해주려고 만들어 둔 것인데요!
이렇게 나눈 이유는 프론트에서 저 에러코드를 보고 각각의 상황에 처리를 다르게 해주려고 만든 것입니다 🙂

2020-06-10 11:44 UTC, YebinK commented on src/main/java/com/peachbros/letsmerge/mission/web/MissionController.java
>  public class MissionController {
흠 저렇게 구현한 이유는 한눈에 어떤 작업을 하는 api인지 보기 편해서 놔둔건데,
api 메소드가 많아지면 중복 제거를 위해서라도 빼는 것이 좋겠네요. 반영하겠습니다!

2020-06-10 11:45 UTC, YebinK commented on src/main/java/com/peachbros/letsmerge/mission/service/MissionService.java
> +
이런 지적 환영 환영 ~

2020-06-10 11:46 UTC, YebinK commented on src/main/java/com/peachbros/letsmerge/mission/model/domain/Mission.java
> +            throw new IllegalArgumentException(String.format("시작 시간(%s)이 종료 시간(%s)보다 뒤에 있습니다.", startDateTime, dueDateTime));
우리 목표가 빠른 배포로 정해진만큼, exception보다 기능 구현을 먼저 완성해야겠다고 생각했어요!
로직에 크게 문제가 되지 않을 부분이라고 생각해서 일단 저렇게 구현해두었습니다.

기능 구현이 완성되면 첫 번째 리팩토링 대상으로 가져가고 싶네요.

2020-06-10 11:51 UTC, merged