Feature/lets merge 14 사용자의 미션 신청/취소/조회 API 작성
PEACH-BROS/lets-merge pull request #25
Opened 2020-07-19 14:40 UTC by YebinK

2020-08-30 11:00 UTC, pci2676 requested changes
리뷰가 많이 늦었습니다!
정말 많이 고생하셨네요!
같이 고민해볼만한 부분에 리뷰를 남겼습니다!

2020-08-30 11:00 UTC, pci2676 commented on src/main/java/com/peachbros/letsmerge/config/auth/SecurityConfig.java
> +                .userService(customOAuth2UserService);
코드 포맷팅 👍

2020-08-30 11:00 UTC, pci2676 commented on src/main/java/com/peachbros/letsmerge/mission/service/AdminMissionService.java
> +    private ObjectMapper mapper;
사용하지 않는 객체네요! 삭제해주세요~

2020-08-30 11:00 UTC, pci2676 commented on src/main/java/com/peachbros/letsmerge/mission/web/AdminMissionController.java
>      }
`StandardResponse`로 반환값을 바꿔 주세요!
URI 정보를 헤더에 추가하고 싶으시다면 HttpServletResponse 를 이용하시면 될 것 같아요~

```java
    @PostMapping
    public StandardResponse<Void> addMission(@RequestBody @Valid MissionCreateRequest request, HttpServletResponse httpServletResponse) {
        MissionResponse response = adminMissionService.addMission(request);
        httpServletResponse.setHeader(HttpHeaders.LOCATION,"/admin/missions/" + response.getId());
        return StandardResponse.empty();
    }
```

2020-08-30 11:00 UTC, pci2676 commented on src/main/java/com/peachbros/letsmerge/user/model/domain/User.java
> +                .filter(info -> Objects.equals(info.getMission().getId(), mission.getId()))
```suggestion
                .filter(info -> info.matchId(mission.getId()))
```
위와 같이 수정하는게 더 낫지 않을까요?

2020-08-30 11:00 UTC, pci2676 commented on src/main/java/com/peachbros/letsmerge/user/model/domain/User.java
> +        assignInfo.setUpdateDateTime(LocalDateTime.now());
두개를 하나의 메소드로 묶어놔도 좋을것 같아요!
set이라는 네이밍말고도 place,change 같은 네이밍도 많이 사용하는것 같아요!

2020-08-30 11:00 UTC, pci2676 commented on src/main/java/com/peachbros/letsmerge/user/model/domain/User.java
> +                .orElseThrow(() -> new NoSuchValueException("존재하지 않는 신청내역입니다."));
ifPresent를 사용하면 이렇게 바꿀수도 있답니다!
```java
assignedMissions.stream()
                .filter(info -> Objects.equals(info.getMission().getId(), mission.getId()))
                .findFirst()
                .ifPresent(assignInfo -> {
                    assignInfo.setAssignStatus(AssignStatus.CANCEL);
                    assignInfo.setUpdateDateTime(LocalDateTime.now());
                    mission.removeAssignInfo(assignInfo);
                });
```
다만 throw를 던져야하는 요구사항이었다면 지금이 더 나을것 같네요!

2020-08-30 11:00 UTC, pci2676 commented on src/main/java/com/peachbros/letsmerge/user/service/UserMissionService.java
> +    }
fetch join으로 바꾸고 `@Transactional`을 제거하는게 좋을 것 같아요~

2020-08-30 11:00 UTC, pci2676 commented on src/main/java/com/peachbros/letsmerge/user/web/UserMissionController.java
> +    //TODO: 신청 취소는 자원 변경 요청. create같이 자원을 생성하는 요청이 아니라 둘이 충돌. 어떻게 하면 좋을까
확인해주세요.

2020-08-30 13:41 UTC, YebinK commented on src/main/java/com/peachbros/letsmerge/mission/service/AdminMissionService.java
> +    private ObjectMapper mapper;
아이코 왜 넣었을까요! 반영했습니다~

2020-08-30 13:56 UTC, YebinK commented on src/main/java/com/peachbros/letsmerge/mission/web/AdminMissionController.java
>      }
통일성 좋네요 👍 
StandardResponse.empty 리턴타입도 제네릭 -> Void로 수정했습니다!

2020-08-30 14:15 UTC, YebinK commented on src/main/java/com/peachbros/letsmerge/user/model/domain/User.java
> +                .filter(info -> Objects.equals(info.getMission().getId(), mission.getId()))
mission.getId() 대신 mission을 통째로 넘겼습니다!
아래 getAssignedMissions 로직도 비슷하게 변경했습니다 🙂

2020-08-30 18:13 UTC, YebinK commented on src/main/java/com/peachbros/letsmerge/user/service/UserMissionService.java
> +    }
User가 Mission을 직접적으로 알지는 못해 fetch join은 사용하기 어려울 것 같아요.
대신, AssignInfoRepository.findByUserId 네임드쿼리를 통해 User에서 Mission까지 탐색하도록 변경했습니다!

2020-08-30 18:18 UTC, YebinK commented on src/main/java/com/peachbros/letsmerge/user/model/domain/User.java
> +                .orElseThrow(() -> new NoSuchValueException("존재하지 않는 신청내역입니다."));
좋은 제안이네요 👍 
하지만 예외 처리를 해주는 것도 여전히 중요해보입니다 🙂
좀 더 리팩토링했으니 확인 부탁드려요~

2020-08-30 18:24 UTC, pci2676 approved these changes
피드백을 반영하니까 정말 깔끔해졌네요!
고생하셨어요 엘리!

2020-08-31 12:22 UTC, slowCoyle approved these changes
고생하셧씁니다.

2020-08-31 12:22 UTC, slowCoyle commented on src/main/java/com/peachbros/letsmerge/AdminPageController.java
>      @GetMapping(produces = MediaType.TEXT_HTML_VALUE)
produces = MediaType.TEXT_HTML_VALUE
오 요놈은 뭐죠 ?!

2020-08-31 12:22 UTC, slowCoyle commented on src/main/java/com/peachbros/letsmerge/config/auth/SecurityConfig.java
> +                .userService(customOAuth2UserService);
이건 when, then 처럼 일부러 포맷팅 해놓지 않은 코드인데...!

2020-08-31 12:22 UTC, slowCoyle commented on src/main/java/com/peachbros/letsmerge/user/web/UserMissionController.java
> +    @GetMapping("/assigned")
assigned 를 넣은 이유는 뭔가요 ?

2020-08-31 12:22 UTC, slowCoyle commented on src/main/java/com/peachbros/letsmerge/user/web/UserMissionController.java
> +    @GetMapping("/assignable")
요곳도 마찬가지

2020-08-31 15:16 UTC, YebinK commented on src/main/java/com/peachbros/letsmerge/config/auth/SecurityConfig.java
> +                .userService(customOAuth2UserService);
그랬군요 되돌려놓았습니다~

2020-09-03 16:23 UTC, merged

2020-09-03 16:25 UTC, YebinK commented on src/main/java/com/peachbros/letsmerge/user/web/UserMissionController.java
> +    @GetMapping("/assigned")
신청한/신청 가능한 미션을 명시적으로 분리하고 싶었습니다!