Feature/lets-merge-7 : 도메인 로직 완성
PEACH-BROS/lets-merge pull request #8
Opened 2020-05-12 12:25 UTC by YebinK

2020-05-13 04:16 UTC, pci2676 requested changes
같이 고민해볼 만한 부분에 리뷰 남겼어요~

2020-05-13 04:16 UTC, pci2676 commented on src/main/java/com/peachbros/letsmerge/mission/model/domain/Mission.java
> +        this.dueDateTime = LocalDateTime.parse(dueDateTime, DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm"));
```suggestion
        this.startDateTime = LocalDateTime.parse(startDateTime, DateTimeFormatter.ofPattern(MISSION_DATE_FORMA));
        this.dueDateTime = LocalDateTime.parse(dueDateTime, DateTimeFormatter.ofPattern(MISSION_DATE_FORMA));
```

깜빡 하신것 같네여

2020-05-13 04:16 UTC, pci2676 commented on src/main/java/com/peachbros/letsmerge/mission/model/domain/Mission.java
> +    public static final String MISSION_DATE_FORMAT = "yyyy-MM-dd HH:mm";
```suggestion
    public static final DateTimeFormatter MISSION_DATE_FORMAT = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm");
```

이렇게 해도 되지 않을까요?
다른 곳에서도 많이 쓰이는 것 같은데 매번 객체를 생성해 주는 것 보다는 하나 만들어서 재사용 하는게 나은 것 같아요

2020-05-13 04:16 UTC, pci2676 commented on src/main/java/com/peachbros/letsmerge/user/model/domain/Users.java
> +public class Users {
사용되는 곳이 없네요 메서드도 없구요 🧐

2020-05-13 04:16 UTC, pci2676 commented on src/main/java/com/peachbros/letsmerge/matcher/model/domain/Matcher.java
> +        ifOneRemains(users, matchedGroup);
이부분 전략 패턴으로 간략하게 바꿔볼수 있을것 같아보여요
그리고 이름만 보면 boolean을 내보내나? 라고 생각할 수 있는데 void로 내부 값을 바꾸는 행위를 하고 있어서 어색한거 같아요

2020-05-13 04:16 UTC, pci2676 commented on src/main/java/com/peachbros/letsmerge/matcher/model/domain/Matcher.java
>  public class Matcher {
이 클래스에서 하는 역할을 Group 일급 컬렉션을 만들어서 생성자에서 그 책임을 위임할 수 있을 것 같다는 생각이 드네요

2020-05-13 04:16 UTC, pci2676 commented on src/test/java/com/peachbros/letsmerge/matcher/model/domain/MatcherTest.java
> +    }
모든 테스트가 하나의 테스트 픽스쳐를 공유하면 테스트 픽스쳐에 의존하게되서 테스트 메서드가 변경에 취약하게 될 수 있어요
귀찮더라고 테스트 메서드에서 쓰이는 데이터를 각각 생성해 주는게 좋을것 같아요

2020-05-13 04:16 UTC, pci2676 commented on src/test/java/com/peachbros/letsmerge/mission/model/domain/MissionTest.java
> +    }
`@CsvSource`이용해서 하나의 테스트 메서드로 이용할 수 있을것 같아요

2020-05-13 04:16 UTC, pci2676 commented on src/main/java/com/peachbros/letsmerge/matcher/model/domain/Matcher.java
>  public class Matcher {
흠 근데 애매하긴 하네요 지금 `Matcher`가 `Group`을 만드는 `Factory` 역할을 하는 것 같아서...
어떻게 생각하시나요?

2020-05-15 00:02 UTC, slowCoyle commented on src/main/java/com/peachbros/letsmerge/mission/model/domain/Mission.java
> +        this.dueDateTime = LocalDateTime.parse(dueDateTime, DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm"));
네 수정했습니다~

2020-05-15 00:08 UTC, slowCoyle commented on src/main/java/com/peachbros/letsmerge/mission/model/domain/Mission.java
> +    public static final String MISSION_DATE_FORMAT = "yyyy-MM-dd HH:mm";
아이고 좋은 생각입니다! :)

2020-05-15 00:09 UTC, YebinK commented on src/main/java/com/peachbros/letsmerge/user/model/domain/Users.java
> +public class Users {
앗! MissionManager에서 일급컬렉션으로 사용하려고 만들어둔 것이었어요!
변경했습니다.

2020-05-18 06:46 UTC, slowCoyle commented on src/main/java/com/peachbros/letsmerge/matcher/model/domain/Matcher.java
>  public class Matcher {
Nice idea!

2020-05-18 06:47 UTC, YebinK commented on src/main/java/com/peachbros/letsmerge/matcher/model/domain/Matcher.java
>  public class Matcher {
Group 생성 로직은 Groups에서 하는 게 맞는거같네요!
하지만 매칭 로직이 복잡해서 Matcher클래스로 빼는 게 맞는거같아요!

2020-05-18 07:21 UTC, slowCoyle commented on src/test/java/com/peachbros/letsmerge/matcher/model/domain/MatcherTest.java
> +    }
BeforeEach와 동일하게 원하는 Size의 Users 를 반환해주는 픽스쳐 생성메서드로 변경하였습니다.

2020-05-18 07:33 UTC, slowCoyle commented on src/test/java/com/peachbros/letsmerge/mission/model/domain/MissionTest.java
> +    }
@MethodResouce를 사용하여 리팩토링하였습니다. 조언 땡큐~

2020-05-18 09:18 UTC, pci2676 approved these changes
좋습니당

2020-05-18 09:19 UTC, YebinK commented on src/main/java/com/peachbros/letsmerge/matcher/model/domain/Matcher.java
> +        ifOneRemains(users, matchedGroup);
변경했습니다! 아직 4, 5명 분배 로직에 대해서는 같이 더 고민해보아요!

2020-05-18 09:49 UTC, ghost approved these changes

2020-05-21 15:06 UTC, merged